version: '3.0'

services:
  avito-shop-service:
      build: .
      container_name: avito-shop-service
      ports:
        - "${SERVER_PORT}:${SERVER_PORT}"
      environment:
        # енвы подключения к БД
        - DATABASE_PORT=${DB_PORT}
        - DATABASE_USER=${DB_USER}
        - DATABASE_PASSWORD=${DB_PASSWORD}
        - DATABASE_NAME=${DB_NAME}
        - DATABASE_HOST=${DB_HOST}
        # порт сервиса
        - SERVER_PORT=${SERVER_PORT}
      depends_on:
        db:
            condition: service_healthy
      networks:
        - internal
  
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal
networks:
  internal: